#!/usr/bin/env bash
set -euo pipefail

trap 'jobs -p | xargs kill' EXIT

CODEC=${CODEC:-wav}
DEVICE_NAME=${DEVICE_NAME:-}
HIFIBERRY_OVERLAY=${HIFIBERRY_OVERLAY:-}
LOOPBACK_SINK=${LOOPBACK_SINK:-alsa_output}
SILENCE_TIMEOUT=${SILENCE_TIMEOUT:-300}
VOLUME_THRESHOLD=${VOLUME_THRESHOLD:-0.005}

# Read CLI arguments
while [[ $# -gt 1 ]]; do
	KEY="$1"
	case ${KEY} in
		-c|--codec)
			CODEC=$2
			shift
			;;
		-d|--device-name)
			DEVICE_NAME=$2
			shift
			;;
		-h|--hifiberry-overlay)
			HIFIBERRY_OVERLAY=$2
			shift
			;;
		-l|--loopback-sink)
			LOOPBACK_SINK=$2
			shift
			;;
		-s|--silence-timeout)
			SILENCE_TIMEOUT=$2
			shift
			;;
		-v|--volume-threshold)
			VOLUME_THRESHOLD=$2
			shift
			;;
		*)
			break
			;;
	esac
	shift
done

BITRATE=320
SAMPLE_RATE=44100
if [[ "${CODEC}" == @(wav|flac) ]]; then
	BITRATE=
fi

SAMPLE_RATE=44100
if [[ "${CODEC}" == @(aac|wav|flac) ]]; then
	SAMPLE_RATE=96000
fi

echo "Quality set to ${CODEC}${BITRATE:+ ${BITRATE}kbps} ${SAMPLE_RATE}Hz"
echo ""


# Set up HiFiBerry devices
# @link https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/
hifiberry() {
	if [[ "${HIFIBERRY_OVERLAY}" == "" ]]; then
		return
	fi
	echo "Configuring HiFiBerry driver ..."

	sudo sed -i 's/^dtparam=audio=on/# dtparam=audio=on/' /boot/config.txt
	sudo sed -i '/^dtoverlay=vc4-kms-v3d/d' /boot/config.txt
	sudo sed -i '1 i\dtoverlay=vc4-kms-v3d,audio=off' /boot/config.txt

	sudo sed -i '/^dtoverlay=hifiberry/d' /boot/config.txt
	sudo sed -i "1 i\dtoverlay=${HIFIBERRY_OVERLAY}" /boot/config.txt

	sudo tee /etc/asound.conf > /dev/null <<-EOF
		pcm.!default {
		  type hw card 0
		}
		ctl.!default {
		  type hw card 0
		}
	EOF
	if [[ -f ~/.asound.conf ]]; then
		rm ~/.asound.conf
	fi

	echo "Reboot required"
	echo ""
}

# apt update singleton alias
UPDATED=false
update() {
	if [[ "${UPDATED}" == "false" ]]; then
		echo "Updating remote packages ..."
		sudo apt update > /dev/null || return 0
		UPDATED=true
	fi
}

# apt install alias
apt_install() {
	update
	echo "Installing '$*' ..."
	sudo apt -y install "$@" > /dev/null
}

# List all Chromecast devices
chromecast_ls() {
	go-chromecast ls --dns-timeout 5 | ansi2txt | grep --invert-match '^error' || true
}

DEVICE_KEYWORDS="All
Every
Entire
Full"
device_match() {
	for KEYWORD in ${DEVICE_KEYWORDS}; do
		while IFS= read -r DEVICE; do
			if echo "${DEVICE}" | grep --ignore-case "${KEYWORD}" &> /dev/null; then
				echo "${DEVICE}"
				return
			fi
		done <<< "$1"
	done
}
chromecast_preferred() {
	CHROMECAST_LS=$(chromecast_ls)
	CHROMECAST_GROUPS=$(echo "${CHROMECAST_LS}" | grep "Google Cast Group" | sed 's/.*device_name="\([^"]\+\)".*/\1/g')
	CHROMECAST_DEVICES=$(echo "${CHROMECAST_LS}" | grep --invert-match "Google Cast Group" | sed 's/.*device_name="\([^"]\+\)".*/\1/g')

	# Cast to a preferred group
	GROUP_DEVICE=$(device_match "${CHROMECAST_GROUPS}")
	if [[ "${GROUP_DEVICE}" != "" ]]; then
		echo "${GROUP_DEVICE}"
		return
	fi

	# Cast to a preferred device
	SINGLE_DEVICE=$(device_match "${CHROMECAST_DEVICES}")
	if [[ "${SINGLE_DEVICE}" != "" ]]; then
		echo "${SINGLE_DEVICE}"
		return
	fi

	# Cast to the first group
	GROUP_DEVICE=$(echo "${CHROMECAST_GROUPS}" | head -1)
	if [[ "${GROUP_DEVICE}" != "" ]]; then
		echo "${GROUP_DEVICE}"
		return
	fi

	# Cast to the first device 
	SINGLE_DEVICE=$(echo "${CHROMECAST_DEVICES}" | head -1)
	if [[ "${SINGLE_DEVICE}" != "" ]]; then
		echo "${SINGLE_DEVICE}"
		return
	fi
}

# Add a PulseAudio loopback if it doesn't already eixst
# @param {string} $1 PulseAudio sink name
loopback() {
	printf "Finding '%s' PulseAudio sink(s) ... " "$1"
	SINKS=""
	LOOP_TIMEOUT=$((SECONDS+60))
	while [[ "${SINKS}" == "" ]]; do
		[[ ${SECONDS} -ge ${LOOP_TIMEOUT} ]] && break
		SINKS=$(pactl list short sinks | grep "$1" | awk '{print $1}' || true)
	done
	echo "#$(echo "${SINKS}" | tr '\n' ',' | sed 's/,$/\n/')"

	for SINK in ${SINKS}; do
		if [[ "$(pactl list short modules | grep module-loopback | grep "sink=${SINK}")" == "" ]]; then
			printf "Adding loopback for sink #%s ... " "${SINK}"
			pactl load-module module-loopback latency_msec=1 sink="${SINK}" > /dev/null
			echo "done"
		fi
	done
}

# Start mkchromecast and add a loopback for it
start() {
	echo "Casting to '${DEVICE_NAME}' ..."
	mkchromecast --debug --encoder-backend ffmpeg \
		--port "$(comm -23 <(seq 49152 65535 | sort) <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) | shuf | head -1)" \
		${CODEC:+--codec "${CODEC}"} ${BITRATE:+--bitrate "${BITRATE}"} ${SAMPLE_RATE:+--sample-rate "${SAMPLE_RATE}"} ${DEVICE_NAME:+--name "${DEVICE_NAME}"} >> /tmp/mkchromecast.log 2>&1 &
	loopback Mkchromecast
	echo "Waiting for cast to start ..."
	LOOP_TIMEOUT=$((SECONDS+60))
	while ! is_playing; do
		if [[ ${SECONDS} -ge ${LOOP_TIMEOUT} ]]; then
			echo "Waiting for cast timed out"
			echo ""
			return 1
		fi
		sleep 1
	done
	echo "Cast started"
	echo ""
}

# Stop mkchromecast if it's running
stop() {
	if pgrep mkchromecast &> /dev/null; then
		echo "Stopping cast ..."
		ps -Afw | grep "$(which mkchromecast)" | grep --invert-match grep | awk '{print $2}' | xargs kill || true
		echo ""
	fi
}

# Return if the Chromecast is playing
is_playing() {
	timeout 5 go-chromecast status --dns-timeout 5 --device-name "${DEVICE_NAME}" | grep -E "PLAYING|BUFFERING" &> /dev/null
	return $?
}

# Get the peak input volume
# @param {number} $1 Seconds to record to determine peak volume
volume() {
	rec -n stat trim 0 "${1:-1}" 2>&1 | grep 'amplitude' | grep --ignore-case 'RMS' | cut -d ':' -f 2 | xargs || echo 0
}


##### Dependencies #####

hifiberry

[[ ! -x "$(command -v pactl)" ]] && apt_install pulseaudio-utils
[[ ! -x "$(command -v rec)" ]] && apt_install sox
[[ ! -x "$(command -v mkchromecast)" ]] && apt_install mkchromecast
[[ ! -x "$(command -v ffmpeg)" ]] && apt_install ffmpeg
if [[ ! -x "$(command -v go-chromecast)" ]]; then
	echo "Installing 'go-chromecast' ..."
	DIR=$(mktemp -d)
	curl --silent https://api.github.com/repos/vishen/go-chromecast/releases/latest | grep 'browser_download_url' | grep 'armv7' | cut -d ':' -f 2,3 | tr -d \" | xargs -n1 wget -qO - | tar -xzf - -C "${DIR}"
	sudo install "${DIR}/go-chromecast" /usr/bin/
fi
[[ ! -x "$(command -v ansi2txt)" ]] && apt_install colorized-logs

##### Main program #####

# shellcheck disable=SC2009
PA_USER=$(ps -Afw | grep "$(which pulseaudio)" | head -1 | awk '{print $1}')
if [[ "${PA_USER}" != "$(whoami)" ]]; then
	echo "This script needs to be run by '${PA_USER}'"
	exit 1
fi

# TODO(cemmer): be smarter if device name is provided
if [[ "$(chromecast_ls)" == "" ]]; then
	echo "Waiting until at least one Chromecast found ..."
	CHROMECAST_LS=""
	while [[ "${CHROMECAST_LS}" == "" ]]; do
		CHROMECAST_LS=$(chromecast_ls)
		sleep 1
	done
	echo "$(echo "${CHROMECAST_LS}" | wc -l | xargs) Chromecast(s) found"
	echo ""
fi

# TODO(cemmer): let this happen multiple times?
DEVICE_NAME=${DEVICE_NAME:-$(chromecast_preferred)}

stop
while true; do
	# TODO(cemmer): wait for Chromecast before anything else

	echo "Waiting for input ..."
	while (( $(echo "$(volume 2) < ${VOLUME_THRESHOLD}" | bc -l) )); do
		sleep 1
	done

	if [[ "${LOOPBACK_SINK}" != "" ]]; then
		loopback "${LOOPBACK_SINK}"
	fi
	start || continue

	SILENCE_DURATION=0
	while true; do
		if (( $(echo "$(volume 5) < ${VOLUME_THRESHOLD}" | bc -l) )); then
			SILENCE_DURATION=$((SILENCE_DURATION+5))
		else
			SILENCE_DURATION=0
		fi
		if [[ ${SILENCE_DURATION} -ge ${SILENCE_TIMEOUT} ]]; then
			echo "Input stopped"
			break
		fi

		if ! is_playing; then
			echo "Chromecast stopped"
			break
		fi
		if ! pgrep mkchromecast &> /dev/null; then
			echo "Chromecast stopped"
			break
		fi
		sleep 2
	done
	stop
done
